version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: bf2042_stats_db
    environment:
      POSTGRES_DB: bf2042_stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/docker-init.sh:/docker-entrypoint-initdb.d/docker-init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
